<div class="mt-4"></div>
<?php
include(TPL_PATH . "accounts/accounts/menu_details.php");
$shipperAccess = 0;
if ($_SESSION['member']['access_shippers'] == 1 ||
        $_SESSION['member']['parent_id'] == $_SESSION['member_id']) {
    $shipperAccess = 1;
}
$i=0;
?>
<script type="text/javascript" src="<?php echo SITE_IN ?>jscripts/jquery.ajaxupload.js"></script>
<script type="text/javascript" src="<?php echo SITE_IN ?>jscripts/dropzone.js"></script>
<link href="<?php echo SITE_IN ?>application/assets/css/dropzone.css" type="text/css" rel="stylesheet"/>
<div align="right" style="clear:both; padding-bottom:5px; padding-top:5px;">
    <img style="vertical-align:middle;" src="<?php echo SITE_IN ?>images/icons/back.png" alt="Back" width="16" height="16"/> 
    <?php
    if ($_SESSION['member']['parent_id'] == $_SESSION['member_id']) {
        ?>
        <a href="<?= getLink("accounts") ?>">&nbsp;Back to the list</a>
        <?php
    } else {
        ?>
        <a href="<?= getLink("accounts", "shippers") ?>">&nbsp;Back to the list</a>
        <?php
    }
    ?>
</div>

<!--mail div-->
<!-- <div id="maildiv">
    <table cellspacing="2" cellpadding="0" border="0">
        <tr>
            <td>@mail_to@</td>
        </tr>
        <tr>
            <td>@mail_subject@</td>
        </tr>
        <tr>
            <td>@mail_body@</td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td>Attachment:&nbsp;</td>
            <td id="mail_file_name" style="font-weight: bold; color: #0052a4; ">&nbsp; </td>
        </tr>
    </table>
</div> -->


<div  class="row">
    <div class="col-6">

         <?php echo formBoxStart("Account Contract Uploading Tool") ?>

                <table cellpadding="0" cellspacing="10" border="0" id="myId" style="width: 96%;">
                    <em><strong> Allowed Extensions: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd.</strong></em>
                    <br>
                    <br>
                    <em>Upload your account contract by dropping your files into the box below.</em>
                    <br>
                    <br>
                    <tr>
                        <td action="#" id="dropzdoc" class="dropzone"></td>
                    </tr>
                </table>
                <?php echo formBoxEnd() ?>

                  <script>
                
                Dropzone.autoDiscover = false;
                var myDropzone = new Dropzone("#dropzdoc", {
                    url: '<?php echo getLink("accounts", "uploadAccountContract", "id", (int) $_GET['id']); ?>',
                    acceptedFiles: ".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.tiff,.wpd",
                    maxFiles: 1,
                    createImageThumbnails: false,
                });

                myDropzone.on("error", function (file, response) {
                    alert('Invalid file extension.\nAllowed file extensions: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd');
                });

                myDropzone.on("processing", function (file, progress) {
                    $('#upload_process').fadeIn();
                    $('#nodocs').hide();
                });

                myDropzone.on("success", function (file, response) {                    
                    location.reload();
                });

                myDropzone.on("addedfile", function (file) {
                    if (this.files.length) {
                        var _i, _len;
                        for (_i = 0, _len = this.files.length; _i < _len - 1; _i++) // -1 to exclude current file
                        {
                            if (this.files[_i].name === file.name)
                            {
                                this.removeFile(file);
                            }
                        }
                    }
                    $('.dz-preview').css('display', 'none');
                    $('.dz-default').css('display', 'block');

                });
            </script>
            <div style="height: 10px;">
                <img id="upload_process" src="<?php echo SITE_IN ?>images/uploading_file.gif" alt="uploading..." style="display: none; height:10px; width:90%;"/>
            </div>

    </div>

    <div class="col-6">
         <div >
                <?php echo formBoxStart("Uploaded Contracts") ?>
                    <em>Below you will find all documents that have been uploaded by users or generated by the system. You can email, view and delete documents uploaded to this account from this section.</em>
                              
                            <!--table containing the list of the documents-->
                            <table class="table table-bordered">
                                <thead>
                                    <tr >
                                        <th>Sno</th>
                                        <th>Name</th>
                                        <th>Upload Date</th>
                                        <th>Upload By</th>
                                        <th>Current</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                        if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") { 
                                            $protocol = "https://";
                                        } else { 
                                            $protocol = "http://";
                                        }
                                       $data = $this->daffny->tpl->document;
                                       $i=1;
                                       if(count($data) > 0){
                                                foreach($data as $value){
                                                    ?>
                                            <tr >
                                                <td align="center"><?php echo $i;?></td>
                                                <td><?php echo $value['name_original'];?></td>
                                                <td align="center"><?php echo date("m/d/Y h:i:s a", strtotime($value['uploaded_at']));?></td>
                                                <td><?php echo $value['uploaded_by_name'];?></td>
                                                <td align="center">
                                                    <?php
                                                        if($value['status']!=0){
                                                            echo '<img src="https://cdn4.iconfinder.com/data/icons/round-buttons/512/green_tick.png" width="10">';
                                                        } else {
                                                            echo '-';
                                                        }
                                                    ?> 
                                                </td>
                                                <td align="center">                                                    
                                                    <a href="<?php echo  $protocol.$_SERVER['HTTP_HOST'].'/account/contractPreview/id/'.$value['id'];?>" download><img alt="Download" title="Download document" src="/images/icons/import.png"/></a>
                                                    &nbsp;&nbsp;
                                                    <a href="#" onclick="sendFile('<?php echo $value['id']; ?>', '<?php echo  $value['name_original'] ?>')">
                                                        <img alt="Email" title="Email document" src="<?php echo  $protocol.$_SERVER['HTTP_HOST']?>/images/icons/file.png" width="20"/>
                                                    </a>
                                                </td>
                                            </tr>
                                                    <?php
                                                    $i++;
                                                }
                                       } else {
                                           echo "<tr><td align='center' colspan='6'><b style='color:red;'>No Account Contract Found for this Shipper</b></td></tr>";
                                       }
                                    ?>
                                    
                                </tbody>
                            </table>
                      
                <?php echo formBoxEnd() ?>
                
                <?php echo backButton(getLink("accounts")) ?>
            </div>
        
    </div>
</div>





<script type="text/javascript">//<![CDATA[

    $(function () {
        new AjaxUpload('#files_upload', {
            action: '<?php echo getLink("accounts", "uploadAccountContract", "id", (int) $_GET['id']) ?>',
            name: 'file',
            onChange: function (file, extension) {
                this.setData({});
            },
            onSubmit: function (file, ext) {
                if (!(ext && /^(pdf|doc|docx|xls|xlsx|jpg|jpeg|png|tiff|wpd)$/.test(ext))) {
                    swal.fire('Invalid file extension.\nAllowed file extensions: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd');
                    return false;
                }
                $('#upload_process').fadeIn();
                $('#nodocs').hide();
            },
            onComplete: function (file, response) {
                $('#upload_process').fadeOut();
                if (response.indexOf('ERROR:') != -1) {
                    swal.fire('Cant\' upload file.\n' + response);
                    return false;
                }
                $(response).appendTo($('#cat'));
            }
        });
    });

    $("#maildiv").dialog({
        modal: true,
        width: 400,
        height: 310,
        title: "Email message with that document attached.",
        hide: 'fade',
        resizable: false,
        draggable: false,
        autoOpen: false,
        buttons: {
            "Submit": function () {
                $.ajax({
                    url: BASE_PATH + 'application/ajax/send_document.php',
                    data: {
                        action: "accounts",
                        file_id: mail_file_id,
                        mail_to: $('#mail_to').val(),
                        mail_subject: $('#mail_subject').val(),
                        mail_body: $('#mail_body').val()
                    },
                    type: 'POST',
                    dataType: 'json',
                    beforeSend: function () {
                        if (!validateMailForm()) {
                            return false;
                        } else {
                            // // $("body").nimbleLoader("show");
                        }
                    },
                    success: function (response) {
                        // $("body").nimbleLoader("hide");
                        if (response.success == true) {
                            $("#maildiv").dialog("close");
                            clearMailForm();
                        }
                        alert(response.message);
                    },
                    complete: function () {
                        // $("body").nimbleLoader("hide");
                    }
                });
            },
            "Cancel": function () {
                $(this).dialog("close");
            }
        }
    });

    //]]></script>
<script>
    $('.files-list').on('click', 'img', function () {
        myDropzone.removeAllFiles(true);
    });
</script>