<? include(TPL_PATH . "accounts/accounts/menu_details.php"); 
$shipperAccess = 0;
if($_SESSION['member']['access_shippers']==1 || 
			   $_SESSION['member']['parent_id']==$_SESSION['member_id'] )
			{
				$shipperAccess = 1;
			}
?>
<script type="text/javascript" src="<?= SITE_IN ?>jscripts/jquery.ajaxupload.js"></script>
<script type="text/javascript" src="<?= SITE_IN ?>jscripts/dropzone.js"></script>
<link href="<?= SITE_IN ?>application/assets/css/dropzone.css" type="text/css" rel="stylesheet"/>
<div align="right" style="clear:both; padding-bottom:5px; padding-top:5px;">
    <img style="vertical-align:middle;" src="<?= SITE_IN ?>images/icons/back.png" alt="Back" width="16" height="16"/> 
    <?php
			if($_SESSION['member']['parent_id']==$_SESSION['member_id'])
			{
			  ?>
              <a href="<?= getLink("accounts") ?>">&nbsp;Back to the list</a>
              <?php
		     }else
			 {
			?>
              <a href="<?= getLink("accounts","shippers") ?>">&nbsp;Back to the list</a>
            <?php	 
			 }
            ?>
</div>
<!-- <div id="maildiv">
    <table cellspacing="2" cellpadding="0" border="0">
        <tr>
            <td>@mail_to@</td>
        </tr>
        <tr>
            <td>@mail_subject@</td>
        </tr>
        <tr>
            <td>@mail_body@</td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td>Attachment:&nbsp;</td>
            <td id="mail_file_name" style="font-weight: bold; color: #0052a4; ">&nbsp;
                
            </td>
        </tr>
    </table>
</div> -->
<table width="100%" cellpadding="1" cellpadding="1" border="0">
<tr>
<td width="33%" valign="top" >
<div style="float:left; width:420px; padding-right:20px;">
    <?= formBoxStart("Document(s) Upload") ?>
	
    <table cellpadding="0" cellspacing="10" border="0" id="myId" style="width: 96%;">
		<em><strong> Allowed Files: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd.</strong></em>
		<br>
		<br>
		<em>Upload your document(s) by dropping your files into the box below.</em>
		<br>
		<br>
        <tr>
            <td action="#" id="dropzdoc" class="dropzone"></td>
        </tr>
    </table>
    <?= formBoxEnd() ?>
</div>
<script>
Dropzone.autoDiscover = false;
var myDropzone = new Dropzone("#dropzdoc",{
 url: '<?php echo getLink("accounts", "upload_file", "id", (int)$_GET['id'] ); ?>',
 acceptedFiles: ".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.tiff,.wpd",
 createImageThumbnails:false,
});

myDropzone.on("error", function(file, response) {
		swal.fire('Invalid file extension.\nAllowed file extensions: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd');
});

myDropzone.on("processing", function(file, progress) {
		 $('#upload_process').fadeIn();
		 $('#nodocs').hide();
});

myDropzone.on("success", function(file,response) {
		$('#upload_process').fadeOut();
		$(response).appendTo($('#cat'));
  });

myDropzone.on("addedfile", function(file) {
    if (this.files.length) {
        var _i, _len;
        for (_i = 0, _len = this.files.length; _i < _len - 1; _i++) // -1 to exclude current file
        {
            if(this.files[_i].name === file.name)
            {
                this.removeFile(file); 
            }
        }
    }
    $('.dz-preview').css('display','none');
    $('.dz-default').css('display','block');
    
});
</script>
</td>
<td width="1%" valign="top" >&nbsp;  </td> 
<td width="65%" valign="top" >
<div style="float:left; width:750px; padding-right:20px;">
    <?= formBoxStart("Uploaded Documents") ?>
    <table cellpadding="0" cellspacing="10" border="0">
	<em>Below you will find all documents that have been uploaded by users or generated by the system. You can email, view and delete documents uploaded to this account from this section.</em>
	<br>
	<br>
        <tr>
            <td colspan="2">
                <div>
                    <ul class="files-list" id="cat">
                        <?php if (isset($this->files) && count($this->files)) { ?>
                            <? foreach ($this->files as $file) { ?>
                                <li id="file-<?= $file['id'] ?>">
                                    <?=$file['img']?>
                                    <?php if($file['insurance']>0){ ?>
                                       <a href="<?=getLink("accounts", "getdocs", "id", $file['id'],"type",1)?>"><?=$file['name_original']?></a>
                                    <?php }else{?>
                                      <a href="<?=getLink("accounts", "getdocs", "id", $file['id'])?>"><?=$file['name_original']?></a>
                                    <?php }?>
                                    (<?=$file['size_formated']?>)
                                    &nbsp;&nbsp;<a href="#" onclick="sendFile('<?=$file['id'];?>', '<?=$file['name_original']?>')">Email</a>
                                    &nbsp;&nbsp;&nbsp;
                                    <?php if($file['insurance']>0){ ?>
                                     
                                    <?php }else{?>
                                      <a href="#"
                                       onclick="return deleteFile('<?php echo getLink("accounts", "delete-file"); ?>', <?php echo $file['id']; ?>);"><img
                                            src="<?= SITE_IN ?>images/icons/delete.png" alt="delete"
                                            style="vertical-align:middle;" width="16" height="16"/></a>
                                    <?php }?>
                                    
                                    
                                </li>
                            <?php } ?>
                        <?php } else { ?>
                            <li id="nodocs">No documents.</li>
                        <?php } ?>
                    </ul>
                </div>
                <div style="height: 20px;"><img id="upload_process" src="<?= SITE_IN ?>images/uploading_file.gif"
                                                alt="uploading..." style="display: none;"/></div>
            </td>
        </tr>
    </table>
    <?= formBoxEnd() ?>
    <br/>
    <?= backButton(getLink("accounts")) ?>
</div>
</td>
</tr>
</table>
<div style="clear:both;">&nbsp;</div>



<script type="text/javascript">//<![CDATA[

    $(function(){
        new AjaxUpload('#files_upload', {
            action: '<?=getLink("accounts", "upload_file", "id", (int)$_GET['id'] ) ?>',
            name: 'file',
            onChange: function(file, extension){
                this.setData({});
            },
            onSubmit: function(file , ext){
                if (!(ext && /^(pdf|doc|docx|xls|xlsx|jpg|jpeg|png|tiff|wpd)$/.test(ext))){
                    swal.fire('Invalid file extension.\nAllowed file extensions: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd');
                    return false;
                }
                $('#upload_process').fadeIn();
                $('#nodocs').hide();
            },
            onComplete : function(file, response){
                $('#upload_process').fadeOut();
                if (response.indexOf('ERROR:') != -1) {
                    alert('Cant\' upload file.\n'+response);
                    return false;
                }
                $(response).appendTo($('#cat'));
            }
        });
    });

    $("#maildiv").dialog({
        modal: true,
        width: 400,
        height: 310,
        title: "Email message with that document attached.",
        hide: 'fade',
        resizable: false,
        draggable: false,
        autoOpen: false,
        buttons: {
            "Submit": function () {
                $.ajax({
                    url: BASE_PATH + 'application/ajax/send_document.php',
                    data: {
                        action: "accounts",
                        file_id: mail_file_id,
                        mail_to: $('#mail_to').val(),
                        mail_subject: $('#mail_subject').val(),
                        mail_body: $('#mail_body').val()
                    },
                    type: 'POST',
                    dataType: 'json',
                    beforeSend: function () {
                        if (!validateMailForm()) {
                            return false;
                        } else {
                            // // $("body").nimbleLoader("show");
                        }
                    },
                    success: function (response) {
                        // $("body").nimbleLoader("hide");
                        if (response.success == true) {
                            $("#maildiv").dialog("close");
                            clearMailForm();
                        }
                        alert(response.message);
                    },
                    complete: function () {
                        // $("body").nimbleLoader("hide");
                    }
                });
            },
            "Cancel": function () {
                $(this).dialog("close");
            }
        }
    });

    //]]></script>
<script>
$('.files-list').on('click','img', function(){ 
    myDropzone.removeAllFiles(true);
});
</script>

