<script type="text/javascript" src="<?= SITE_IN ?>jscripts/jquery.ajaxupload.js"></script>
<div style="padding-top:15px;">
    <?php include('order_menu.php');  ?>
</div>
<br/>
<div id="maildiv">
    <table cellspacing="2" cellpadding="0" border="0">
        <tr>
            <td>@mail_to@</td>
        </tr>
        <tr>
            <td>@mail_subject@</td>
        </tr>
        <tr>
            <td>@mail_body@</td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td>Attachment:&nbsp;</td>
            <td id="mail_file_name" style="font-weight: bold; color: #0052a4; ">
                &nbsp;
            </td>
        </tr>
    </table>
</div>
<h3>Order #<?= $this->entity->getNumber() ?> Documents</h3>
<br>
</br>
<table width="100%" cellpadding="1" cellpadding="1" border="0">
<tr>
<td width="33%" valign="top" >
<div style="float:left; width:420px; padding-right:20px;">
    <?= formBoxStart() ?>
    <table cellpadding="0" cellspacing="10" border="0">
		<em>Select "Choose File" to upload your document to the order.</em>
		<br>
		<br>
		<em><strong> Allowed Files: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd.</strong></em>
		<br>
		<br>
        <tr>
            <td>@files_upload@</td>
        </tr>
    </table>
    <?= formBoxEnd() ?>
</div>

</td> 
<td width="1%" valign="top" >&nbsp;  </td>
<td width="65%" valign="top" >
<div style="float:left; width:750px; padding-right:20px;">
	<?= formBoxStart() ?>
    <table cellpadding="0" cellspacing="10" border="0">
	<em>Below you will find all documents that have been uploaded by users or generated by the system. You can email, view and delete documents uploaded to this order from this section.</em>
	<br>
	<br>
        <tr>
            <td colspan="2">
                <div>
                    <ul class="files-list" id="cat">
                        <?php if (isset($this->files) && count($this->files)) { ?>
                            <? foreach ($this->files as $file) { ?>
                                <li id="file-<?= $file['id'] ?>">
                                    <?=$file['img']?>
									&nbsp;&nbsp;
                                    <a href="<?=getLink("orders", "getdocs", "id", $file['id'])?>"><?=$file['name_original']?></a>&nbsp;&nbsp;
                                    (<?=$file['size_formated']?>)
                                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick="sendFile('<?=$file['id'];?>', '<?=$file['name_original']?>')">Email</a>
                                    &nbsp;&nbsp;&nbsp;&nbsp;<a <?=strtolower($file['type'])=='pdf'?"target=\"_blank\"":""?> href="<?=getLink("orders", "getdocs", "id", $file['id'])?>">View</a>
                                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="#"
                                       onclick="return deleteFile('<?php echo getLink("orders", "delete-file"); ?>', <?php echo $file['id']; ?>);"><img
                                            src="<?= SITE_IN ?>images/icons/delete.png" alt="delete"
                                            style="vertical-align:middle;" width="16" height="16"/></a>
                                </li>
                            <?php } ?>
                        <?php } else { ?>
                            <li id="nodocs">No documents.</li>
                        <?php } ?>
                    </ul>
                </div>
                <div style="height: 20px;"><img id="upload_process" src="<?= SITE_IN ?>images/uploading_file.gif"
                                                alt="uploading..." style="display: none;"/></div>
            </td>
        </tr>
    </table>
    <?= formBoxEnd() ?>
</div>
	</td>
	</tr>
</table>
<div style="clear:both;">&nbsp;</div>
<script type="text/javascript">//<![CDATA[
    $(function(){
        new AjaxUpload('#files_upload', {
            action: '<?=getLink("orders", "upload_file", "id", (int)$_GET['id'] ) ?>',
            name: 'file',
            onChange: function(file, extension){
                this.setData({});
            },
            onSubmit: function(file , ext){
                if (!(ext && /^(pdf|doc|docx|xls|xlsx|jpg|jpeg|png|tiff|wpd)$/.test(ext))){
                    alert('Invalid file extension.\nAllowed file extensions: pdf, doc, docx, xls, xlsx, jpg, jpeg, png, tiff, wpd');
                    return false;
                }
                $('#upload_process').fadeIn();
                $('#nodocs').hide();
            },
            onComplete : function(file, response){
                $('#upload_process').fadeOut();
                if (response.indexOf('ERROR:') != -1) {
                    alert('Cant\' upload file.\n'+response);
                    return false;
                }
                $(response).appendTo($('#cat'));
            }
        });
    });

    $("#maildiv").dialog({
        modal: true,
        width: 400,
        height: 310,
        title: "Email message with that document attached.",
        hide: 'fade',
        resizable: false,
        draggable: false,
        autoOpen: false,
        buttons: {
            "Submit": function () {
                $.ajax({
                    url: BASE_PATH + 'application/ajax/send_document.php',
                    data: {
                        action: "entity",
                        file_id: mail_file_id,
                        mail_to: $('#mail_to').val(),
                        mail_subject: $('#mail_subject').val(),
                        mail_body: $('#mail_body').val()
                    },
                    type: 'POST',
                    dataType: 'json',
                    beforeSend: function () {
                        if (!validateMailForm()) {
                            return false;
                        } else {
                            // // $("body").nimbleLoader("show");
                        }
                    },
                    success: function (response) {
                        // $("body").nimbleLoader("hide");
                        if (response.success == true) {
                            $("#maildiv").dialog("close");
                            clearMailForm();
                        }
                        alert(response.message);
                    },
                    complete: function () {
                        // $("body").nimbleLoader("hide");
                    }
                });
            },
            "Cancel": function () {
                $(this).dialog("close");
            }
        }
    });

    //]]></script>